Telemetry jar fix

diff --git a/kubernetes/3-observability/3-identity-servcie.yml b/kubernetes/3-observability/3-identity-servcie.yml
--- a/kubernetes/3-observability/3-identity-servcie.yml
+++ b/kubernetes/3-observability/3-identity-servcie.yml
@@ -26,11 +26,22 @@ spec:
                 echo "Waiting for discovery-service to be UP";
                 sleep 5;
               done
+        - name: init-opentelemetry
+          image: curlimages/curl:latest
+          command: [ "/bin/sh", "-c" ]
+          args:
+            - curl -L -o /app/libs/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.0/opentelemetry-javaagent.jar
+          volumeMounts:
+            - name: otel-agent
+              mountPath: /app/libs
       containers:
         - name: identity-service
           image: justamitsaha/ms-identity-service:observability
           ports:
             - containerPort: 8090
+          volumeMounts:
+            - name: otel-agent
+              mountPath: /app/libs   # open telemetry  will be loaded at this path by init container
           env:
             - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
               valueFrom:
@@ -83,30 +94,35 @@ spec:
                   key: OTEL_METRICS_EXPORTER
             - name: OTEL_SERVICE_NAME
               value: identity-service
-#          startupProbe:
-#            httpGet:
-#              path: /identity/actuator/health
-#              port: 8090
-#            initialDelaySeconds: 30 # Wait 10 seconds before first check
-#            periodSeconds: 5 # Check every 5 seconds
-#            failureThreshold: 6 # Fail after 6 unsuccessful checks
-#
-#          livenessProbe:
-#            exec:
-#              command:
-#                - /bin/sh
-#                - -c
-#                - >
-#                  curl --fail --silent http://localhost:8090/identity/user/findById/1 | grep Amit || exit 1
-#            initialDelaySeconds: 30
-#            periodSeconds: 10
-#
-#          readinessProbe:
-#            httpGet:
-#              path: /identity/actuator/health
-#              port: 8090
-#            initialDelaySeconds: 30
-#            periodSeconds: 10
+          startupProbe:
+            httpGet:
+              path: /identity/actuator/health
+              port: 8090
+            initialDelaySeconds: 60 # Wait 60 seconds before first check
+            periodSeconds: 10 # Check every 10 seconds
+            failureThreshold: 10 # Fail after 10 unsuccessful checks
+
+          livenessProbe:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - >
+                  curl --fail --silent http://localhost:8090/identity/user/findById/1 | grep Amit || exit 1
+            initialDelaySeconds: 30
+            periodSeconds: 10
+
+          readinessProbe:
+            httpGet:
+              path: /identity/actuator/health
+              port: 8090
+            initialDelaySeconds: 30
+            periodSeconds: 10
+
+      volumes:
+        - name: otel-agent
+          emptyDir: {}
+
 ---
 apiVersion: v1
 kind: Service
diff --git a/kubernetes/3-observability/4-product-service.yml b/kubernetes/3-observability/4-product-service.yml
--- a/kubernetes/3-observability/4-product-service.yml
+++ b/kubernetes/3-observability/4-product-service.yml
@@ -26,11 +26,22 @@ spec:
                 echo "Waiting for identity-service to be UP";
                 sleep 20;
               done;
+        - name: init-opentelemetry
+          image: curlimages/curl:latest
+          command: [ "/bin/sh", "-c" ]
+          args:
+            - curl -L -o /app/libs/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.0/opentelemetry-javaagent.jar
+          volumeMounts:
+            - name: otel-agent
+              mountPath: /app/libs
       containers:
         - name: product-service
           image: justamitsaha/ms-product-service:observability
           ports:
             - containerPort: 8091
+          volumeMounts:
+            - name: otel-agent
+              mountPath: /app/libs   # open telemetry  will be loaded at this path by init container
           env:
             - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
               valueFrom:
@@ -63,21 +74,35 @@ spec:
                   key: OTEL_METRICS_EXPORTER
             - name: OTEL_SERVICE_NAME
               value: product-service
-#          livenessProbe:
-#            exec:
-#              command:
-#                - /bin/sh
-#                - -c
-#                - >
-#                  curl --fail --silent http://localhost:8091/product/findById/100 | grep productDescription || exit 1
-#            initialDelaySeconds: 30
-#            periodSeconds: 10
-#          readinessProbe:
-#            httpGet:
-#              path: /product/actuator/health
-#              port: 8091
-#            initialDelaySeconds: 30
-#            periodSeconds: 10
+
+          startupProbe:
+            httpGet:
+              path: /product/actuator/health
+              port: 8091
+            initialDelaySeconds: 60 # Wait 60 seconds before first check
+            periodSeconds: 10 # Check every 10 seconds
+            failureThreshold: 10 # Fail after 10 unsuccessful checks
+
+          livenessProbe:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - >
+                  curl --fail --silent http://localhost:8091/product/findById/100 | grep productDescription || exit 1
+            initialDelaySeconds: 30
+            periodSeconds: 10
+          readinessProbe:
+            httpGet:
+              path: /product/actuator/health
+              port: 8091
+            initialDelaySeconds: 30
+            periodSeconds: 10
+
+      volumes:
+        - name: otel-agent
+          emptyDir: {}
+
 ---
 apiVersion: v1
 kind: Service
